# Generated by Django 3.2.7 on 2022-04-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='product_name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='product_price')),
                ('description', models.TextField(max_length=1000, verbose_name='product_description')),
                ('image_url', models.URLField(max_length=3000)),
            ],
        ),
    ]
