# Generated by Django 3.2.7 on 2022-04-09 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_productrating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrating',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.customer'),
        ),
    ]
