# Generated by Django 3.2.7 on 2022-04-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_productrating_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 'very poor'), (2, 'poor'), (3, 'good'), (4, 'very good'), (5, 'excellent')], null=True, verbose_name='product_rating'),
        ),
        migrations.DeleteModel(
            name='ProductRating',
        ),
    ]
