# Generated by Django 3.2.7 on 2022-04-16 19:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20220409_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinstance',
            name='delivery_status',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('status', models.CharField(choices=[('P', 'Pending'), ('D', 'Delivered')], default='P', max_length=1)),
                ('date_made', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.customer')),
                ('order_cart', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.cart')),
            ],
        ),
    ]
