# Generated by Django 3.2.7 on 2022-04-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20220409_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=2000)),
            ],
        ),
    ]
