# Generated by Django 3.2.7 on 2022-04-17 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_cart_cart_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cart_id',
            new_name='cart_uuid',
        ),
    ]
